#!/bin/bash
##
# ------------------------------------------------------------------------
#     Copyright (C) 2012 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       001_oh_prologue_blade1
# Description:
#       A script to download all software.
# Note:
#       Sourced via LOTC cluster install script execution during
#       the post installation phase.
##
# Usage:
#       Used during APG43L maiden installation.
##
# Output:
#       None.
##
# Changelog:
# - Tue Mar 13 2012 - Paolo Palmieri (epaopal)
#       First version.
##

# Non-initialized variables are forbidden
#set -u
set -x

function get_hook_path() {
  local FOLDER="${HOOKS_DIR}"
  if [ "${FOLDER}" == "" ]; then
    FOLDER="/tmp/hooks_execute_dir"
    if [ -d ${FOLDER} ]; then
      echo "${FOLDER}"
    else
      echo "ERROR: The hook path is not configured by LOTC!"; echo "Aborting"; echo ""; exit 1
    fi
  else
    if [ -d ${FOLDER} ]; then
      echo "${FOLDER}"
    else
      echo "ERROR: The hook path is wrongly provided by LOTC!"; echo "Aborting"; echo ""; exit 1
    fi
  fi
}

function init_system() {
  # Common functions sourcing
  local hook_path=$( get_hook_path )
  local common_functions="${hook_path}/non_exec-common_functions"
  . ${common_functions}
}

#                                              __    __   _______   _   __    _
#                                             |  \  /  | |  ___  | | | |  \  | |
#                                             |   \/   | | |___| | | | |   \ | |
#                                             | |\  /| | |  ___  | | | | |\ \| |
#                                             | | \/ | | | |   | | | | | | \   |
#                                             |_|    |_| |_|   |_| |_| |_|  \__|
#
main() {
  echo "--- main() begin"

  # Local variables
  local MI_PATH="/cluster/mi"
  local MI_LOGS="logs"
  local NODE_NAME=$( cat /etc/cluster/nodes/this/hostname )

  # Initialize the system
  init_system

  echo "--- main() end"

  # Copying log files
  if [ -d $MI_PATH/$MI_LOGS ]; then
    pushd "$MI_PATH/$MI_LOGS" > /dev/null 2>&1
    if [ ! -d $NODE_NAME ]; then mkdir $NODE_NAME; fi
    pushd "$NODE_NAME" > /dev/null 2>&1
    cp /root/*.log $MI_PATH/$MI_LOGS/$NODE_NAME/
    popd > /dev/null 2>&1; popd > /dev/null 2>&1
  else
    abort "Unable to find the $MI_PATH/$MI_LOGS folder"
  fi
}

# Main

echo "APG43L: Post-installation prologue hook for SC-2-2 node."

main "@"
exit $TRUE

# End of file
