#!/bin/bash
# Autogenerated deployment file for AIT-TA
# Do not modify...

node_id=$(</etc/cluster/nodes/this/id)
node_type=$(</etc/cluster/nodes/this/type)
node_ctrl_dir=/etc/cluster/nodes/control

# AIT-TA should be started once all nodes are up.
# A hack to achieve this is to install it on the second controller
# after DRBD sync is done, as all payloads should have started by then.
# If there is only one controller then install it on node 1.
# TODO: Possibly implement a node monitor to check for ssh connectivity.

ctrl_cnt=$(ls $node_ctrl_dir | wc -l)
if [ $ctrl_cnt -eq 2 ]; then
	if [[ $node_id -ne 2 || $node_type != "control" ]]; then
		exit 0
	fi
elif [[ $node_type != "control" ]]; then
	exit 0
fi

old_path=$(pwd)
dep_scr_path=$(cd $(dirname $0) && pwd)
cd $old_path

if [ ! -d /home/ait/ ]; then
	mkdir -p /home/ait/
fi
install $dep_scr_path/non_exec-ait-repo.conf /home/ait//ait-repo.conf
if [ ! -d /home/ait/ ]; then
	mkdir -p /home/ait/
fi
install $dep_scr_path/non_exec-NOBCK /home/ait//NOBCK
if [ ! -d /home/ait/ ]; then
	mkdir -p /home/ait/
fi

install $dep_scr_path/non_exec-FORCE /home/ait//FORCE
install $dep_scr_path/dxtoolbox-ait-ta-cxp9019385-2.16.0-1.noarch.rpm /cluster/rpms/dxtoolbox-ait-ta-cxp9019385-2.16.0-1.noarch.rpm
cluster rpm -a dxtoolbox-ait-ta-cxp9019385-2.16.0-1.noarch.rpm -n $node_id
cluster rpm -A -n $node_id
/opt/ait/etc/init.d/ait_ta start

